name: CLI Tests

on:
  pull_request:
    branches: [main]
    paths:
      - "packages/cli/**"
      - ".github/workflows/test-cli.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.7.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build:core && pnpm build:deployer && pnpm build:clients && pnpm build:cli

      - name: Run CLI tests
        run: pnpm test:cli
        env:
          NODE_OPTIONS: "--max_old_space_size=8096"
